In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
col_names=['pregnant','Plasma_glucose','bp','skin_fold','insulin','mass_index','pedigree','age','class']
df= pd.read_csv('pima-indians-diabetes.csv',names=col_names)

In [3]:
df.drop(df.index[:9],inplace=True)

In [4]:
errors = {'coerce','raise'}
df = df.apply(pd.to_numeric,errors = 'coerce')

In [5]:
df.isnull().sum()
df.dropna()

pregnant  Plasma_glucose    bp  skin_fold  insulin  mass_index  pedigree  \
9           6           148.0  72.0       35.0      0.0        33.6     0.627   
10          1            85.0  66.0       29.0      0.0        26.6     0.351   
11          8           183.0  64.0        0.0      0.0        23.3     0.672   
12          1            89.0  66.0       23.0     94.0        28.1     0.167   
13          0           137.0  40.0       35.0    168.0        43.1     2.288   
..        ...             ...   ...        ...      ...         ...       ...   
772        10           101.0  76.0       48.0    180.0        32.9     0.171   
773         2           122.0  70.0       27.0      0.0        36.8     0.340   
774         5           121.0  72.0       23.0    112.0        26.2     0.245   
775         1           126.0  60.0        0.0      0.0        30.1     0.349   
776         1            93.0  70.0       31.0      0.0        30.4     0.315   

      age  class  
9    50.0    1.0  
10   31.0    0.0  
11   32.0    1.0  
12   21.0    0.0  
13   33.0    1.0  
..    ...    ...  
772  63.0    0.0  
773  27.0    0.0  
774  30.0    0.0  
775  47.0    1.0  
776  23.0    0.0  

[768 rows x 9 columns]

In [6]:
y=df['class']
X=df.drop('class',axis=1)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=0)


In [8]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')
rf_model.fit(X_train,y_train)
y_pred=rf_model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 


[[95 12]
 [17 30]]
              precision    recall  f1-score   support

         0.0       0.85      0.89      0.87       107
         1.0       0.71      0.64      0.67        47

    accuracy                           0.81       154
   macro avg       0.78      0.76      0.77       154
weighted avg       0.81      0.81      0.81       154

Accuracy :  81.16883116883116


In [9]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=5)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 


[[88 19]
 [13 34]]
              precision    recall  f1-score   support

         0.0       0.87      0.82      0.85       107
         1.0       0.64      0.72      0.68        47

    accuracy                           0.79       154
   macro avg       0.76      0.77      0.76       154
weighted avg       0.80      0.79      0.80       154

Accuracy :  79.22077922077922


In [10]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=9)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 


[[90 17]
 [18 29]]
              precision    recall  f1-score   support

         0.0       0.83      0.84      0.84       107
         1.0       0.63      0.62      0.62        47

    accuracy                           0.77       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.77      0.77      0.77       154

Accuracy :  77.27272727272727


In [11]:
#ANN

In [12]:
import tensorflow as tf

In [13]:
model =tf.keras.models.Sequential([
          tf.keras.layers.Dense(64,activation='relu',input_shape=(8,)),
          tf.keras.layers.Dense(128,activation='relu'),
          tf.keras.layers.Dense(128,activation='relu'),
          tf.keras.layers.Dropout(0.2),
          tf.keras.layers.Dense(1, activation='sigmoid')
])

In [14]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [15]:
model.fit(X_train, y_train,epochs = 100,batch_size=32)

Train on 614 samples
Epoch 1/100
614/614 [==============================] - 0s 396us/sample - loss: 2.2557 - accuracy: 0.5668
Epoch 2/100
614/614 [==============================] - 0s 88us/sample - loss: 1.3482 - accuracy: 0.5847
Epoch 3/100
614/614 [==============================] - 0s 94us/sample - loss: 1.0955 - accuracy: 0.5668
Epoch 4/100
614/614 [==============================] - 0s 96us/sample - loss: 0.7892 - accuracy: 0.6270
Epoch 5/100
614/614 [==============================] - 0s 84us/sample - loss: 0.7387 - accuracy: 0.6466
Epoch 6/100
614/614 [==============================] - 0s 94us/sample - loss: 0.6577 - accuracy: 0.6743
Epoch 7/100
614/614 [==============================] - 0s 87us/sample - loss: 0.6553 - accuracy: 0.6482
Epoch 8/100
614/614 [==============================] - 0s 86us/sample - loss: 0.6098 - accuracy: 0.6629
Epoch 9/100
614/614 [==============================] - 0s 139us/sample - loss: 0.6063 - accuracy: 0.6889
Epoch 10/100
614/614 [===================

In [16]:
y_pred= model.evaluate(X_test,y_test)

154/154 [==============================] - 0s 606us/sample - loss: 0.5657 - accuracy: 0.7532
