In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
column_names = ['Age','Sex','On_thyroxine','Query_on_thyroxine',
                'On_antithyroid_medication','Sick','Pregnant','Thyroid_surgery','I131_treatment','Query_hypothyroid',
                'Query_hyperthyroid','Lithium','Goitre','Tumor','Hypopituitary','Psych','TSH','T3','TT4','T4U','FTI','class']
df = pd.read_csv('thyroid.csv',names = column_names)


In [3]:
df

Age     Sex On_thyroxine  \
0                            @relation thyroid     NaN          NaN   
1                    @attribute Age real [0.01   0.97]          NaN   
2                    @attribute Sex integer [0      1]          NaN   
3           @attribute On_thyroxine integer [0      1]          NaN   
4     @attribute Query_on_thyroxine integer [0      1]          NaN   
...                                        ...     ...          ...   
7221                                      0.36       0            0   
7222                                      0.27       0            0   
7223                                      0.26       1            0   
7224                                      0.95       0            0   
7225                                      0.51       0            0   

     Query_on_thyroxine On_antithyroid_medication Sick Pregnant  \
0                   NaN                       NaN  NaN      NaN   
1                   NaN                       NaN  NaN      NaN   
2                   NaN                       NaN  NaN      NaN   
3                   NaN                       NaN  NaN      NaN   
4                   NaN                       NaN  NaN      NaN   
...                 ...                       ...  ...      ...   
7221                  0                         0    0        0   
7222                  0                         0    0        0   
7223                  0                         0    0        0   
7224                  0                         0    0        0   
7225                  0                         0    0        0   

     Thyroid_surgery I131_treatment Query_hypothyroid  ... Goitre Tumor  \
0                NaN            NaN               NaN  ...    NaN   NaN   
1                NaN            NaN               NaN  ...    NaN   NaN   
2                NaN            NaN               NaN  ...    NaN   NaN   
3                NaN            NaN               NaN  ...    NaN   NaN   
4                NaN            NaN               NaN  ...    NaN   NaN   
...              ...            ...               ...  ...    ...   ...   
7221               0              0                 0  ...      0     0   
7222               0              0                 0  ...      0     0   
7223               0              0                 0  ...      0     0   
7224               0              0                 0  ...      0     0   
7225               0              0                 0  ...      0     0   

     Hypopituitary Psych       TSH       T3       TT4     T4U       FTI class  
0              NaN   NaN       NaN      NaN       NaN     NaN       NaN   NaN  
1              NaN   NaN       NaN      NaN       NaN     NaN       NaN   NaN  
2              NaN   NaN       NaN      NaN       NaN     NaN       NaN   NaN  
3              NaN   NaN       NaN      NaN       NaN     NaN       NaN   NaN  
4              NaN   NaN       NaN      NaN       NaN     NaN       NaN   NaN  
...            ...   ...       ...      ...       ...     ...       ...   ...  
7221             0     0   0.00232   0.0201   0.11329   0.096   0.11776   3.0  
7222             0     0    0.0015   0.0201      0.09   0.082      0.11   3.0  
7223             0     0     0.001   0.0201      0.08   0.075     0.107   3.0  
7224             0     0    0.0016   0.0201     0.098   0.091     0.108   3.0  
7225             0     1   0.00076   0.0201      0.09   0.067     0.134   3.0  

[7226 rows x 22 columns]

In [4]:
df = df[26:]

In [5]:
df=df.reset_index(drop=True)
df

Age Sex On_thyroxine Query_on_thyroxine On_antithyroid_medication Sick  \
0     0.73   0            1                  0                         0    0   
1     0.24   0            0                  0                         0    0   
2     0.47   0            0                  0                         0    0   
3     0.64   1            0                  0                         0    0   
4     0.23   0            0                  0                         0    0   
...    ...  ..          ...                ...                       ...  ...   
7195  0.36   0            0                  0                         0    0   
7196  0.27   0            0                  0                         0    0   
7197  0.26   1            0                  0                         0    0   
7198  0.95   0            0                  0                         0    0   
7199  0.51   0            0                  0                         0    0   

     Pregnant Thyroid_surgery I131_treatment Query_hypothyroid  ... Goitre  \
0           0               0              1                 0  ...      0   
1           0               0              0                 0  ...      0   
2           0               0              0                 0  ...      0   
3           0               0              0                 0  ...      0   
4           0               0              0                 0  ...      0   
...       ...             ...            ...               ...  ...    ...   
7195        0               0              0                 0  ...      0   
7196        0               0              0                 0  ...      0   
7197        0               0              0                 0  ...      0   
7198        0               0              0                 0  ...      0   
7199        0               0              0                 0  ...      0   

     Tumor Hypopituitary Psych       TSH       T3       TT4     T4U       FTI  \
0        0             0     0    0.0006    0.015      0.12   0.082     0.146   
1        0             0     0   0.00025     0.03     0.143   0.133     0.108   
2        0             0     0    0.0019    0.024     0.102   0.131     0.078   
3        0             0     0    0.0009    0.017     0.077    0.09     0.085   
4        0             0     0   0.00025    0.026     0.139    0.09     0.153   
...    ...           ...   ...       ...      ...       ...     ...       ...   
7195     0             0     0   0.00232   0.0201   0.11329   0.096   0.11776   
7196     0             0     0    0.0015   0.0201      0.09   0.082      0.11   
7197     0             0     0     0.001   0.0201      0.08   0.075     0.107   
7198     0             0     0    0.0016   0.0201     0.098   0.091     0.108   
7199     0             0     1   0.00076   0.0201      0.09   0.067     0.134   

     class  
0      3.0  
1      3.0  
2      3.0  
3      3.0  
4      3.0  
...    ...  
7195   3.0  
7196   3.0  
7197   3.0  
7198   3.0  
7199   3.0  

[7200 rows x 22 columns]

In [6]:
df.shape

(7200, 22)

In [7]:
y=df['class']
X=df.drop('class',axis=1)

In [8]:
df['class'] = df['class'].replace(1.0,0.0)
df['class'] = df['class'].replace(2.0,1.0)
df['class'] = df['class'].replace(3.0,1.0)


In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=0)


In [10]:
from sklearn import preprocessing
min_max_scaler= preprocessing.MinMaxScaler()
min_max_scaler.fit_transform(X)
X

Age Sex On_thyroxine Query_on_thyroxine On_antithyroid_medication Sick  \
0     0.73   0            1                  0                         0    0   
1     0.24   0            0                  0                         0    0   
2     0.47   0            0                  0                         0    0   
3     0.64   1            0                  0                         0    0   
4     0.23   0            0                  0                         0    0   
...    ...  ..          ...                ...                       ...  ...   
7195  0.36   0            0                  0                         0    0   
7196  0.27   0            0                  0                         0    0   
7197  0.26   1            0                  0                         0    0   
7198  0.95   0            0                  0                         0    0   
7199  0.51   0            0                  0                         0    0   

     Pregnant Thyroid_surgery I131_treatment Query_hypothyroid  ... Lithium  \
0           0               0              1                 0  ...       0   
1           0               0              0                 0  ...       0   
2           0               0              0                 0  ...       0   
3           0               0              0                 0  ...       0   
4           0               0              0                 0  ...       0   
...       ...             ...            ...               ...  ...     ...   
7195        0               0              0                 0  ...       0   
7196        0               0              0                 0  ...       0   
7197        0               0              0                 0  ...       0   
7198        0               0              0                 0  ...       0   
7199        0               0              0                 0  ...       0   

     Goitre Tumor Hypopituitary Psych       TSH       T3       TT4     T4U  \
0         0     0             0     0    0.0006    0.015      0.12   0.082   
1         0     0             0     0   0.00025     0.03     0.143   0.133   
2         0     0             0     0    0.0019    0.024     0.102   0.131   
3         0     0             0     0    0.0009    0.017     0.077    0.09   
4         0     0             0     0   0.00025    0.026     0.139    0.09   
...     ...   ...           ...   ...       ...      ...       ...     ...   
7195      0     0             0     0   0.00232   0.0201   0.11329   0.096   
7196      0     0             0     0    0.0015   0.0201      0.09   0.082   
7197      0     0             0     0     0.001   0.0201      0.08   0.075   
7198      0     0             0     0    0.0016   0.0201     0.098   0.091   
7199      0     0             0     1   0.00076   0.0201      0.09   0.067   

           FTI  
0        0.146  
1        0.108  
2        0.078  
3        0.085  
4        0.153  
...        ...  
7195   0.11776  
7196      0.11  
7197     0.107  
7198     0.108  
7199     0.134  

[7200 rows x 21 columns]

In [11]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')
rf_model.fit(X_train,y_train)
y_pred=rf_model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 


[[  33    6]
 [   3 1398]]
              precision    recall  f1-score   support

         0.0       0.92      0.85      0.88        39
         1.0       1.00      1.00      1.00      1401

    accuracy                           0.99      1440
   macro avg       0.96      0.92      0.94      1440
weighted avg       0.99      0.99      0.99      1440

Accuracy :  99.375


In [12]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=5)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
   

[[  37    2]
 [   3 1398]]
              precision    recall  f1-score   support

         0.0       0.93      0.95      0.94        39
         1.0       1.00      1.00      1.00      1401

    accuracy                           1.00      1440
   macro avg       0.96      0.97      0.97      1440
weighted avg       1.00      1.00      1.00      1440

Accuracy :  99.65277777777779


In [13]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=9)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 


[[   5   34]
 [   0 1401]]
              precision    recall  f1-score   support

         0.0       1.00      0.13      0.23        39
         1.0       0.98      1.00      0.99      1401

    accuracy                           0.98      1440
   macro avg       0.99      0.56      0.61      1440
weighted avg       0.98      0.98      0.97      1440

Accuracy :  97.63888888888889


In [14]:
model =tf.keras.models.Sequential([
          tf.keras.layers.Dense(128,activation='relu',input_shape=(21,)),
          tf.keras.layers.Dense(512,activation='relu'),
          tf.keras.layers.Dense(1024,activation='relu'),
          tf.keras.layers.Dropout(0.2),
          tf.keras.layers.Dense(3, activation='softmax')
])

In [15]:
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

In [16]:
model.fit(X_train, y_train,epochs = 5,batch_size=32,verbose=2)

Train on 5760 samples
Epoch 1/5
5760/5760 - 2s - loss: 0.1099 - accuracy: 0.9774
Epoch 2/5
5760/5760 - 2s - loss: 0.0322 - accuracy: 0.9898
Epoch 3/5
5760/5760 - 2s - loss: 0.0257 - accuracy: 0.9915
Epoch 4/5
5760/5760 - 2s - loss: 0.0221 - accuracy: 0.9925
Epoch 5/5
5760/5760 - 2s - loss: 0.0201 - accuracy: 0.9924


In [17]:
y_pred= model.evaluate(X_test,y_test)


1440/1440 [==============================] - 0s 166us/sample - loss: 0.0624 - accuracy: 0.9833
